### ISSUE TITLE
Which BSD license does this project use?

### ISSUE THREAD

**Issue by hughmcmaster** [vgavro/samsung-mdc#12]
I'm planning to package samsung-mdc for Debian and Ubuntu. Part of the packaging process involves confirming a package's licensing and copyright.

Your licence information just lists `BSD`, but which version do you mean? There are several:
[BSD-1-Clause](https://spdx.org/licenses/BSD-1-Clause.html)
[BSD-2-Clause](https://spdx.org/licenses/BSD-2-Clause.html)
[BSD-3-Clause](https://spdx.org/licenses/BSD-3-Clause.html)
[BSD-4-Clause](https://spdx.org/licenses/BSD-4-Clause.html)

If you can confirm which BSD licence `samsung-mdc` is released under, that would be very helpful.

**Comment by vgavro** [comment]
@hughmcmaster thanks for interest in that, I genuinely didn't know there are different versions, just wanted *as permissive license as possible*.
[BSD-3-Clause](https://spdx.org/licenses/BSD-3-Clause.html) should be more permissive than original BSD, so i guess I should go with that (?)
Should I replace "BSD" with "BSD-3" in `setup.py.license`, or add LICENSE file with BSD-3-Clause?

**Comment by vgavro** [comment]
Specified BSD-3-Clause license and added license file to package! Thanks for pointing this out!

**Comment by hughmcmaster** [comment]
> Specified BSD-3-Clause license and added license file to package (released new version)!

I was going to recommend both options.

Thank you for responding so quickly.
