### ISSUE TITLE
Forget key command ch list

### ISSUE THREAD

**Issue by Anti-T97** [vgavro/samsung-mdc#13]
Hi,

You forget to add command key on virtual remote to this key : ch list
To choose the channel you add in you scheduler

Thank to add it.

**Comment by Anti-T97** [comment]
And add choose MagicInfo Channel too :)
![Capture d’écran du 2024-07-02 12-20-50](https://github.com/vgavro/samsung-mdc/assets/137830325/ad206db4-4bc6-4226-929e-90614a3c326e)

**Comment by vgavro** [comment]
Hey, looks like you're doing right **EXCEPT** you need to use `samsung_mdc.fields.IntHL` field for this (_Integer represented by high+low bytes_).
Plz ensure it's working with:
```
DATA = [IntHL('CHANNEL_NUMBER')]
```

also note that `range` is not implemented for IntHL, so IF there is range limit in documentation (?) you may also want to add "range" code there and ensure it's shown in cli help interface

Plz confirm it's working or better provide Pull Request? Thank you!

**Comment by vgavro** [comment]
@Anti-T97 released new version 1.13.0 with 7 new commands, you may see changes in commit https://github.com/vgavro/samsung-mdc/commit/64ef0dfd093011ae6e05f726a2be0a3707e52859, plz ensure it's working for you? closing ticket for now!

**Comment by Anti-T97** [comment]
%> samsung-mdc 0@192.168.1.17 magicinfo_channel 2 
0@192.168.1.17 TypeError: Int.pack() takes 2 positional arguments but 3 were given

Always have this error

**Comment by vgavro** [comment]
@Anti-T97 thanks for quick response, fixed in 1.13.1 https://github.com/vgavro/samsung-mdc/commit/28a2352fc44ac973916502fe36cff0e15816481d , plz check again

**Comment by Anti-T97** [comment]
It work fine now :+1: 

Thank a lot
