### ISSUE TITLE
Error cmd panel_on_time on QM55B-T 

### ISSUE THREAD

**Issue by Anti-T97** [vgavro/samsung-mdc#15]
0@192.168.1.49 QM55B-T
./venv/bin/samsung-mdc --verbose 0@192.168.1.49 panel_on_time

192.168.1.49 Connected
192.168.1.49 Sent aa:83:00:00:83
192.168.1.49 Recv aa:ff:00:05:41:83:00:06:86:54
0@192.168.1.49 MDCResponseError: ('Unparsed data left', b'\x86')
Task exception was never retrieved
future: <Task finished name='Task-1' coro=<register_command.<locals>._cmd.<locals>.call() done, defined at /home/antit/samsung/samsung-mdc/samsung_mdc/cli.py:541> exception=MDCResponseError('Unparsed data left', b'\x86')>
Traceback (most recent call last):
  File "/home/antit/samsung/samsung-mdc/samsung_mdc/cli.py", line 543, in call
    await mdc_call(connection, display_id)
  File "/home/antit/samsung/samsung-mdc/samsung_mdc/cli.py", line 389, in mdc_call
    _repr(await self.mdc_command(connection, display_id,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/antit/samsung/samsung-mdc/samsung_mdc/command.py", line 57, in __call__
    return self.parse_response_data(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/antit/samsung/samsung-mdc/samsung_mdc/commands.py", line 779, in parse_response_data
    return super().parse_response_data(data)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/antit/samsung/samsung-mdc/samsung_mdc/command.py", line 88, in parse_response_data
    raise MDCResponseError('Unparsed data left', data[cursor:])
samsung_mdc.exceptions.MDCResponseError: ('Unparsed data left', b'\x86')

When this cmd work on older screen
0@192.168.1.35 QM43R
% ./venv/bin/samsung-mdc --verbose 0@192.168.1.35 panel_on_time
192.168.1.35 Connected
192.168.1.35 Sent aa:83:00:00:83
192.168.1.35 Recv aa:ff:00:04:41:83:a0:28:8f
0@192.168.1.35 41000

The protocol doc
![image](https://github.com/user-attachments/assets/fb009126-2a80-4f0a-a813-6e04f8aac100)

**Comment by vgavro** [comment]
fixed in version 1.14.1, thanks for reporting!
It looks like panel_on_time is represented with 3-bytes on newer models, which makes sense.
Changed it to have dynamic value instead of having 2-bytes (like in docs).

**Comment by Anti-T97** [comment]
It work fine.
Thank Victor
