### ISSUE TITLE
network_ap_config not working as expected

### ISSUE THREAD

**Issue by YFornasari** [vgavro/samsung-mdc#16]
First of all wanted to thank you for creating this software.
Trying it out to manage 33 Samsung TV's.
I was trying to change the network from one SSID to another with network_ap_config, but it doesn't seem to work.
It disconnects the TV from current network, but doesn't change over to the new network.

I have only tested this on a QM55R-B so far with Software Verison: T-KTM2ELAKUC-2330.0, will try with some other models we have when I have some time.

Running Samsung-MDC on Ubuntu 24.04 LTS with Python 3.12.3

samsung_mdc@samsungmdc:~/samsung-mdc$ ./venv/bin/samsung-mdc 0@192.168.14.159:1515 power ON
0@192.168.14.159:1515 <POWER_STATE.ON:1>
samsung_mdc@samsungmdc:~/samsung-mdc$ ./venv/bin/samsung-mdc 0@192.168.14.159:1515 network_ap_config SSID PASSWORD
0@192.168.14.159:1515 MDCReadTimeoutError: [Errno Response header read timeout] b''

**Comment by vgavro** [comment]
looks like it works exactly as reported before: https://github.com/vgavro/samsung-mdc/issues/10
if you're SURE that device is not changing network (how can you be sure?) - I don't understand reason than. If you eventually do - plz report so I can add to readme. As for now - it LOOKS like it's trying to reconnect whether SSID/PASSWORD right or wrong.

just a little clarification - command SENT SUCCESSFULLY (and confirmed by TCP), command is waiting RESPONSE after sent - response HEADER (exactly first byte) - didn't came in meaningful timeout. Only reason is - TV/Monitor is dropping current network on successfull command receive BEFORE sending acknowledge (as required by protocol).

**Comment by vgavro** [comment]
@YFornasari was your problem resolved? have you tried with wrong SSID/PASSWORD and got same results? are you sure that network wasn't changed (by pinging samsung mdc in parallel, for example) ?

**Comment by YFornasari** [comment]
Unfortunately still can't get it to work.

The TV disconnects from the current network, if I reboot the TV I reconnects to the current network.
Looks like it disconnects before sending the SSID and Password to connect to the other wifi.

When I try a wrong password I get the same result.
Tried with another tv (Samsung QB49R), same result.
________________________________
Van: Victor Gavro ***@***.***>
Verzonden: zaterdag 3 augustus 2024 22:12
Aan: vgavro/samsung-mdc ***@***.***>
CC: YFornasari ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [vgavro/samsung-mdc] network_ap_config not working as expected (Issue #16)


@YFornasari<https://github.com/YFornasari> was your problem resolved? have you tried with wrong SSID/PASSWORD and got same results? are you sure that network wasn't changed (by pinging samsung mdc in parallel, for example) ?

**Comment by vgavro** [comment]
@YFornasari thanks for your tests!

So what we know for sure:
* it disconnects before sending response (ACK) (reported by 2 people from at least 3 devices) - for wrong AND proper  SSID/PASSWORD. "Looks like it disconnects before sending the SSID and Password to connect to the other wifi." - for sure it's the issue, I agree with you.
* it connects successfully after that by at least 1 report for proper SSID/PASSWORD...

My guess is - SSID/PASSWORD may be wrong OR wifi connection to this specific ssid unsupported by samsung device for any reason - some unsupported WPA/WPA2 algorithms, other wifi compatibility (newer ieee standard than expected or frequency), samsung bug with tricky password?, wifi is too far away, etc)

**Comment by YFornasari** [comment]
Forgot to mention that I can actually connect to the network when I use the remote to type in the password.
Just doesn't work with Samsung mdc network_ap_config.

Double checked the password and it's definitely correct.
To be sure I tried connecting to another different SSID, but still no luck.

After using network_ap_config and looking in the wireless settings of the TV I still have to type the password from the network I pushed. However I can connect to the old network without typing the password.

**Comment by vgavro** [comment]
@YFornasari thanks for your very detailed report, it will be very useful to know this in context of other reports on this matter that may occur later.
Still at this stage - I can't do anything for debug or help unfortunately.
Reset device as last resort, but i don't think it's the case here.
Command is implemented by specification (you can double-check using `--verbose` option and MDC Protocol specification attached to this repository). For now regarding command itself what I can say for sure - this command ALWAYS returns read timeout (because of network change).
I'll try personally on samsung as soon as i'll be near one, but it may take some time and still may not resolve your issue.

**Comment by YFornasari** [comment]
Alright, I'll check once more with --verbose.
If you need me to test anything in the future just let me know.
