### ISSUE TITLE
Invalid mute status

### ISSUE THREAD

**Issue by DPStokesNZ** [vgavro/samsung-mdc#18]
There's an invalid hex status code for the unavailable option in the MUTE class. Nice and easy fix.

samsung_mdc/commands.py
Current:
NONE = 0x255  # Unavailable

Correct:
NONE = 0xFF  # Unavailable

This will prevent the following exception when querying devices that have no audio, e.g.: SBB-CX4BPES
raise ve_exc
ValueError: 255 is not a valid MUTE.MUTE_STATE

**Comment by vgavro** [comment]
Thanks, fixed and released in [new version!](https://github.com/vgavro/samsung-mdc/releases/tag/v1.14.2)

**Comment by DPStokesNZ** [comment]
Thank you!
