### ISSUE TITLE
video_wall_model set method noop

### ISSUE THREAD

**Issue by helge000** [vgavro/samsung-mdc#2]
The `video_wall_model` setter currently disables the videwall mode and does not change the model 

## Version
1.8.0

## Steps:
```
$ samsung-mdc --version
samsung-mdc, version 1.8.0

$ samsung-mdc -v 0@10.200.1.205 video_wall_model
10.200.1.205 Connected
10.200.1.205 Sent aa:89:00:00:89
10.200.1.205 Recv aa:ff:00:04:41:89:22:03:f2
0@10.200.1.205 2,2 3

$ samsung-mdc -v 0@10.200.1.205 video_wall_model 2,2 4
10.200.1.205 Connected
10.200.1.205 Sent aa:89:00:23:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:04:b0
10.200.1.205 Recv aa:ff:00:04:41:89:00:00:cd
0@10.200.1.205 0,0 0

$ samsung-mdc -v 0@10.200.1.205 video_wall_state
10.200.1.205 Connected
10.200.1.205 Sent aa:84:00:00:84
10.200.1.205 Recv aa:ff:00:03:41:84:00:c7
0@10.200.1.205 <VIDEO_WALL_STATE.OFF:0>

$ samsung-mdc -v 0@10.200.1.205 video_wall_state 1
10.200.1.205 Connected
10.200.1.205 Sent aa:84:00:01:01:86
10.200.1.205 Recv aa:ff:00:03:41:84:01:c8
0@10.200.1.205 <VIDEO_WALL_STATE.ON:1>
```

**Comment by helge000** [comment]
The pack_video_wall_model method result looks off to me; in #1 I had my issues formatting this. AFAIKT it should send in my example above:

```python
b'\x22\x04'
```
As per the manual I have:
![Manual](https://user-images.githubusercontent.com/13696924/144081802-ff6ebb75-f568-4586-aa32-d441e3e4aef0.png)

The above call should send:
```
aa:89:00:02:22:04:<checksum>
```
Interestingly there is no error :)

## Off topic
Your remarks form #1 - thanks for releasing it so quickly since I need the other commands.

> There is no need to keep SERIAL of video wall in same field as coordinates. So I moved it to separate field.

Totally makes sense to me, was in my first version but had issues with the packer methods

> pack_videowall implementation wasn't clear for me - so I rewrite it - hope it still works the same)

I think this our culprit still; 
- [does it actually swap X/Y? ](https://github.com/vgavro/samsung-mdc/blob/e206ab4c3df2b1f10defc06eee7d1ae0bb232544/samsung_mdc/utils.py#L68)

> What was the reason for limit for x * y < 90 and serial < 90? I believe this should be 100 or 99 for 10x10 video wall? There is no such limit in latest protocol documentation (see MDC-Protocol.pdf from root repository), there is 225 limit (15x15 max), but I believe it's ok to leave such errors to samsung anyway (to NAK error), or add separate error for exceeding limit (don't mix it with wrong tuple length i mean) - but really I wouldn't bother).

Right, good solution. However, after seeing the above the `ǸAK` seems to be just to disable the video wall.

**Comment by vgavro** [comment]
@helge000 Thanks for that! fixed in commit above. Please ensure everything is ok now.
