### ISSUE TITLE
INV: MDC add input_source WEB_BROWSER (Samsung Display Web Browser)

### ISSUE THREAD

**Issue by ionescu77** [vgavro/samsung-mdc#5]
Hello,

great work here with this project. I'd be happy to contribute.

## Issue
I could not change `SOURCE` to `Web Browser` (the Samsung DSP Web-Browser). I thought IWB is what I need, but it won't do anything on my display Samsung Digital Signage QMR Series (Tizen 4.0)

## Resolution
I discovered there is no entry to "Web Browser".

```py
        INTERNAL_USB = 0x62
        URL_LAUNCHER = 0x63
        IWB = 0x64
```

https://github.com/vgavro/samsung-mdc/blob/cff614044f9f638dce7296b3aed26b8d4f6c025f/samsung_mdc/commands.py#L153

Web Browser is using `0x65` (IWB is `0x64`) - according to the MDC Spec 2020 `MDC_Protocol_2020_mdc_ppmxxm6x_Protocolv15.0c.pdf`:

<img width="474" alt="Screenshot 2022-09-30 at 11 23 16" src="https://user-images.githubusercontent.com/8016748/193226174-2d2a4f8f-b208-4e3a-8909-71dfa15b4925.png">

I will add an entry called `WEB_BROWSER`:

```py
        IWB = 0x64
        WEB_BROWSER = 0x65
```

## TEST
Changed it and tested with a display I have available here and it works now.
For example I can switch now between `HDMI1` and `WEB_BROWSER`

**Comment by ionescu77** [comment]
Wait... hmmm

`IWB` and `Web Browser` are to different things?

**Comment by vgavro** [comment]
tnx for contribution!
released new version https://pypi.org/project/python-samsung-mdc/1.11.2/
