### ISSUE TITLE
Cannot access the file server to download the MDC unified 

### ISSUE THREAD

**Issue by abdlmlaekluttei** [vgavro/samsung-mdc#8]
the web server asks for credential to be able to download any thing from the server

**Comment by vgavro** [comment]
This webserver and especially "MDC Unified" program is not a part of this project, and it is possible it's not avaliable for public download at all anymore. "MDC Unified" was developed, distributed and copyrighted by Samsung, so it is possible that you can get it from them, if you have "partner" support or something like this.
Feel free to create pull request to update outdated link and maybe add some comments there.
