### ISSUE TITLE
Do not receiving device responses

### ISSUE THREAD

**Issue by moraespc** [vgavro/samsung-mdc#9]
Greetings!
I'm trying to use this Samsung-MDC implementation but when I try to send any command through the CLI I get an header response error.
I read something about authentication token, perhaps i'm missing something here... My TV model is  QN90BA 43 (QN43QN90BAGXZD)
Here's an exception snapshot:

> C:\Users\User>samsung-mdc -v -m tcp 1@192.168.11.115:1516 status
> 192.168.11.115:1516 Connected
> 192.168.11.115:1516 Sent aa:00:01:00:01
> 1@192.168.11.115:1516 MDCReadTimeoutError: [Errno Response header read timeout] b''
> Task exception was never retrieved
> future: <Task finished name='Task-1' coro=<register_command.<locals>._cmd.<locals>.call() done, defined at C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\samsung_mdc\cli.py:540> exception=MDCReadTimeoutError('Response header read timeout', b'')>
> Traceback (most recent call last):
>   File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 490, in wait_for
>     return fut.result()
>            ^^^^^^^^^^^^
>   File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\asyncio\streams.py", line 690, in read
>     await self._wait_for_data('read')
>   File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\asyncio\streams.py", line 522, in _wait_for_data
>     await self._waiter
> asyncio.exceptions.CancelledError
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\samsung_mdc\connection.py", line 26, in wait_for_read
>     return await asyncio.wait_for(reader.read(count), timeout)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 492, in wait_for
>     raise exceptions.TimeoutError() from exc
> TimeoutError
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\samsung_mdc\cli.py", line 542, in call
>     await mdc_call(connection, display_id)
>   File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\samsung_mdc\cli.py", line 388, in mdc_call
>     _repr(await self.mdc_command(connection, display_id,
>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\samsung_mdc\command.py", line 51, in call
>     await connection.send(
>   File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\samsung_mdc\connection.py", line 172, in send
>     resp = await wait_for_read(self.reader, 4, self.timeout,
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\samsung_mdc\connection.py", line 28, in wait_for_read
>     raise MDCReadTimeoutError(reason, bytes(reader._buffer)) from exc
> samsung_mdc.exceptions.MDCReadTimeoutError: [Errno Response header read timeout] b''

**Comment by vgavro** [comment]
Hi, was your issue solved? I don't remember exactly, but maybe this can happen if you have PIN authentication enabled, maybe if you try to use TLS with PIN (even wrong) it can give you different kind of response? If I had a lucky guess, then we should definitely update README Troubleshooting section with that! I'm not using Samsung devices at the time, unfortunately, so can't check it.

**Comment by rohitsawant310** [comment]
Hi Victor,
Thank you for providing the wonderful Samsung MDC library. 
Currently, I am encountering an MDCReadTimeoutError: ('Response header read timeout', b'') while using the command:
'samsung-mdc -v -m tcp 0@172.16.20.220:1515 serial_number' on Linux.
My model is a Samsung QM55B, and PIN authentication is disabled.
Please check the logs below -:

>     
> root@cube:/tmp/python-samsung-mdc-1.12.1# samsung-mdc -v -m tcp 0@172.16.20.220:1515 serial_number
> 172.16.20.220:1515 Connected 
> 172.16.20.220:1515 Sent aa:0b:00:00:0b
> 0@172.16.20.220:1515 MDCReadTimeoutError: ('Response header read timeout', b'')
> Task exception was never retrieved
> future: <Task finished coro=<register_command.<locals>._cmd.<locals>.call() done, defined at /tmp/python-samsung-mdc-1.12.1/samsung_mdc/cli.py:540> exception=MDCReadTimeoutError('Response header read timeout', b'')>
> Traceback (most recent call last):
>   File "/tmp/python-samsung-mdc-1.12.1/samsung_mdc/connection.py", line 26, in wait_for_read
>     return await asyncio.wait_for(reader.read(count), timeout)
>   File "/usr/lib/python3.7/asyncio/tasks.py", line 423, in wait_for
>     raise futures.TimeoutError()
> concurrent.futures._base.TimeoutError
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/tmp/python-samsung-mdc-1.12.1/samsung_mdc/cli.py", line 542, in call
>     await mdc_call(connection, display_id)
>   File "/tmp/python-samsung-mdc-1.12.1/samsung_mdc/cli.py", line 389, in mdc_call
>     *args)))
>   File "/tmp/python-samsung-mdc-1.12.1/samsung_mdc/command.py", line 54, in __call__
>     self.pack_payload_data(data) if data else []
>   File "/tmp/python-samsung-mdc-1.12.1/samsung_mdc/connection.py", line 173, in send
>     'Response header read timeout')
>   File "/tmp/python-samsung-mdc-1.12.1/samsung_mdc/connection.py", line 28, in wait_for_read
>     raise MDCReadTimeoutError(reason, bytes(reader._buffer)) from exc
> samsung_mdc.exceptions.MDCReadTimeoutError: ('Response header read timeout', b'')
> root@cube:/tmp/python-samsung-mdc-1.12.1# nc -nzv 172.16.20.220 1515
> Connection to 172.16.20.220 1515 port [tcp/*] succeeded!
> root@cube:/tmp/python-samsung-mdc-1.12.1# 
>

**Comment by vgavro** [comment]
Have you tried to use different display_id? Like `1@172.16.20.220:1515` ? Please answer if it would help (see https://github.com/vgavro/samsung-mdc#troubleshooting) if this is the case, I'll update README to make it more clear for timeout errors.

**Comment by rohitsawant310** [comment]
@vgavro 
Yes, I tried with a different display_id as well; however, I am still encountering the same error. 

> root@cube:/tmp/python-samsung-mdc-1.12.1# samsung-mdc -v -m tcp 1@172.16.20.220:1515 serial_number
> 172.16.20.220:1515 Connected
> 172.16.20.220:1515 Sent aa:0b:01:00:0c
> 1@172.16.20.220:1515 MDCReadTimeoutError: ('Response header read timeout', b'')
> Task exception was never retrieved
> future: <Task finished coro=<register_command.<locals>._cmd.<locals>.call() done, defined at /tmp/python-samsung-mdc-1.12.1/samsung_mdc/cli.py:540> exception=MDCReadTimeoutError('Response header read timeout', b'')>
> Traceback (most recent call last):
>   File "/tmp/python-samsung-mdc-1.12.1/samsung_mdc/connection.py", line 26, in wait_for_read
>     return await asyncio.wait_for(reader.read(count), timeout)
>   File "/usr/lib/python3.7/asyncio/tasks.py", line 423, in wait_for
>     raise futures.TimeoutError()
> concurrent.futures._base.TimeoutError
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/tmp/python-samsung-mdc-1.12.1/samsung_mdc/cli.py", line 542, in call
>     await mdc_call(connection, display_id)
>   File "/tmp/python-samsung-mdc-1.12.1/samsung_mdc/cli.py", line 389, in mdc_call
>     *args)))
>   File "/tmp/python-samsung-mdc-1.12.1/samsung_mdc/command.py", line 54, in __call__
>     self.pack_payload_data(data) if data else []
>   File "/tmp/python-samsung-mdc-1.12.1/samsung_mdc/connection.py", line 173, in send
>     'Response header read timeout')
>   File "/tmp/python-samsung-mdc-1.12.1/samsung_mdc/connection.py", line 28, in wait_for_read
>     raise MDCReadTimeoutError(reason, bytes(reader._buffer)) from exc
> samsung_mdc.exceptions.MDCReadTimeoutError: ('Response header read timeout', b'')

**Comment by vgavro** [comment]
I don't have any suggestions except everything in https://github.com/vgavro/samsung-mdc#troubleshooting section I'm afraid, try everything out there - experiment with `status` command, try 255, 254 display_id, reboot device, try to find display_id in UI, factory reset is also an option.
For some reason, the device is indeed LISTENING on 1515 port but do not respond, while connection is not dropped (I guess?), so as last resort after factory reset may be network-related issues (if you still see "Connected" on :1515 and on :1516 port, for example, it's not normal)

Plz answer explicitly what steps you tried, because for example in your last message it's not clear if you tested 255 and 254 display_id for example.

**Comment by rohitsawant310** [comment]
I checked the display_id = 1 from the UI and then attempted to run the command 'samsung-mdc -v -m tcp 1@172.16.20.220:1515 status.' I encountered the same error.

> 
> root@cube:/tmp/python-samsung-mdc-1.12.1# samsung-mdc -v -m tcp 1@172.16.20.220:1515 status
> 172.16.20.220:1515 Connected
> 172.16.20.220:1515 Sent aa:00:01:00:01
> 1@172.16.20.220:1515 MDCReadTimeoutError: ('Response header read timeout', b'')
> Task exception was never retrieved
> future: <Task finished coro=<register_command.<locals>._cmd.<locals>.call() done, defined at /tmp/python-samsung-mdc-1.12.1/samsung_mdc/cli.py:540> exception=MDCReadTimeoutError('Response header read timeout', b'')>
> Traceback (most recent call last):
>   File "/tmp/python-samsung-mdc-1.12.1/samsung_mdc/connection.py", line 26, in wait_for_read
>     return await asyncio.wait_for(reader.read(count), timeout)
>   File "/usr/lib/python3.7/asyncio/tasks.py", line 423, in wait_for
>     raise futures.TimeoutError()
> concurrent.futures._base.TimeoutError
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/tmp/python-samsung-mdc-1.12.1/samsung_mdc/cli.py", line 542, in call
>     await mdc_call(connection, display_id)
>   File "/tmp/python-samsung-mdc-1.12.1/samsung_mdc/cli.py", line 389, in mdc_call
>     *args)))
>   File "/tmp/python-samsung-mdc-1.12.1/samsung_mdc/command.py", line 54, in __call__
>     self.pack_payload_data(data) if data else []
>   File "/tmp/python-samsung-mdc-1.12.1/samsung_mdc/connection.py", line 173, in send
>     'Response header read timeout')
>   File "/tmp/python-samsung-mdc-1.12.1/samsung_mdc/connection.py", line 28, in wait_for_read
>     raise MDCReadTimeoutError(reason, bytes(reader._buffer)) from exc
> samsung_mdc.exceptions.MDCReadTimeoutError: ('Response header read timeout', b'')

for port 1516 :

> root@cube:/tmp/python-samsung-mdc-1.12.1# samsung-mdc -v -m tcp 1@172.16.20.220:1516 status
> 1@172.16.20.220:1516 MDCTimeoutError: Connect timeout
> Task exception was never retrieved

I observed a connection on port 1515 but not on port 1516

**Comment by vgavro** [comment]
@rohitsawant310 still, there are plenty of options left to try in the troubleshooting section. Good Luck and plz try to update this ticket if anything would work for you so we can update readme with that. thank you!

**Comment by rohitsawant310** [comment]
Hi @vgavro 
After an investigation, it was found that incoming traffic on port 1515 was blocked by the firewall. While outbound data transmission functioned correctly, the inability to receive incoming data necessitated a review of firewall settings. Subsequent adjustments were made to permit incoming traffic on port 1515, resulting in the resolution of the issue and enabling bidirectional communication. As a result, MDC responses can now be received successfully.
Thank you @vgavro  for support.

**Comment by wizAIsoezuen** [comment]
had the same error. My display was connected via wifi and I was trying to use tcp. In the samsung display settings the connection cable type needs to be set to RJ45 instead of rs232. Worked afterwards
